name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your main branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101'

      - name: Restore dependencies
        run: dotnet restore ./CICD/CICD.csproj

      - name: Build the application
        run: dotnet build ./CICD/CICD.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./CICD/CICD.csproj --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Docker image
        run: |
          docker build -t cicdapp .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Stop and remove existing container
        run: |
          docker stop cicdapp || true
          docker rm cicdapp || true

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name cicdapp cicdapp
